version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - mvn install # or your custom build command
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar # Or specify the artifact files you want to output
